spring:
  cloud:
    gateway:
      routes:
        - id: test-gateway
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq-gateway
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
    nacos:
      discovery:
        server-addr: 180.76.180.113:8848
  application:
    name: service-gateway
server:
  port: 10001